### ISSUE TITLE
Inbox force closing 

### ISSUE THREAD

**Issue by Blaiser47** [zephiK/Bug-tracker#1]
Your device: Nexus 6 

Which ROM version are you using? (provide download link)
Latest 27-05-2015 build 
https://www.androidfilehost.com/?fid=23991606952610862
What kernel are you using - included in the ROM or from another source?
(provide xda/download link)
Modified Franco included in rom
What steps will reproduce the problem?
1. Clean flash
2. Boot up and install only inbox by gmail and SysLog to get a log
3. Open inbox, add account read 10-15 emails, pretty quickly (open email, back, next email, back etc.) 

What is the expected result? What do you see instead?
Expect inbox to work fine.  Instead after several emails, it hangs,  goes to white screen and says unfortunately inbox has stopped. Included logs for two occurrences of this. 

Is the result seen after a clean flash too? Yup.  Been having it for weeks on several versions of chroma, through and inbox app update, gapps updates, etc. This issue does not seem to occur on  AOSIP,  but I much prefer Chroma! 

Log 1
https://www.dropbox.com/s/f40rwrdta9302w4/2015-05-31_19.58.zip?dl=0

Log 2
https://www.dropbox.com/s/d4avfkmapcef505/2015-05-31_19.59.zip?dl=0

**Comment by zephiK** [comment]
Already discussed this problem with you in the N6 forum thread.
