### ISSUE TITLE
Incoming call (before answer) activate proximity sensor

### ISSUE THREAD

**Issue by dcop7** [zephiK/Bug-tracker#2]
Do you use Xposed framework? No.

Your device: Nexus 4

Which ROM version are you using? (provide download link): Chroma 2015-05-27

What kernel are you using - included in the ROM or from another source? Hellscore b78
(provide xda/download link)

What steps will reproduce the problem?
1. Someone is calling you
2. Before you answer or decline the call, if there are an object near the proximity sensor, the screen turns off

What is the expected result? What do you see instead? The screen should only turn off after answer the call. This only happens in Chroma, I've tested in Euphoria and this does not happen.

Is the result seen after a clean flash too? Yes.

Attach a logcat and/or a last_kmsg . Without this,the issue is impossible
to fix.
I don't think a logcat will be helpful because it appears to be some kind of function that is working when is not supposed to be, and other users are reporting the same problem (it should be easy to reproduce).

**Comment by zephiK** [comment]
Closing this bug report because this is based on a obsolete source.
